language: node_js
node_js: stable

sudo: false

install: true  # yarn bug

addons:
  firefox: "45.0"

os:
  - linux
#  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi

before_script:
  - npm i -g npm@^5.3.0
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi  # Protractor CI

after_failure:
  - cat /home/travis/build/mgechev/angular-seed/npm-debug.log

branches:
  only: master

notifications:
  email: true
  webhooks:
    urls: https://webhooks.gitter.im/e/565e4b2fed3b96c1b964
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

cache:
  directories: node_modules

script:
  - npm run tests.all

