language: node_js

node_js:
  - "4.0"
  - "4.1"

sudo: false

services:

before_install:
  - "npm update -g npm"
  - "npm --version"
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:

notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master